# Generated by Django 2.1.7 on 2019-03-22 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=255)),
                ('alamat', models.CharField(max_length=255)),
                ('umur', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'anggota',
            },
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=255)),
                ('penerbit', models.CharField(max_length=255)),
                ('tanggal_terbit', models.DateField()),
            ],
            options={
                'db_table': 'buku',
            },
        ),
        migrations.CreateModel(
            name='DetilSewa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('jumlah', models.IntegerField(default=0)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='test_perpus.Buku')),
            ],
            options={
                'db_table': 'detilsewa',
            },
        ),
        migrations.CreateModel(
            name='Sewa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=255)),
                ('tanggal_pinjam', models.DateField()),
                ('tanggal_kembali', models.DateField()),
                ('anggota', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='test_perpus.Anggota')),
            ],
            options={
                'db_table': 'sewa',
            },
        ),
        migrations.AddField(
            model_name='detilsewa',
            name='sewa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='test_perpus.Sewa'),
        ),
    ]
