# Generated by Django 2.1.7 on 2019-03-22 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_perpus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sewa',
            name='nama',
        ),
    ]
