# Generated by Django 2.1.7 on 2019-05-14 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_perpus', '0002_remove_sewa_nama'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nama_kategori', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'kategori',
            },
        ),
        migrations.AddField(
            model_name='buku',
            name='kategori',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='test_perpus.Kategori'),
        ),
    ]
