# Generated by Django 2.1.7 on 2019-03-20 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(default='1234', max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('lat', models.DecimalField(blank=True, decimal_places=20, default=0, max_digits=50)),
                ('long', models.DecimalField(blank=True, decimal_places=20, default=0, max_digits=50)),
                ('status', models.CharField(default='Down', max_length=15)),
            ],
            options={
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='DeviceReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('power', models.CharField(max_length=255)),
                ('flag', models.CharField(max_length=255)),
                ('temperature', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='test_device.Device')),
            ],
            options={
                'db_table': 'device_report',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vendor',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='test_device.Vendor'),
        ),
    ]
